chore: add local dir jar loading ICIJ/datashare#910

diff --git a/datashare-dist/src/main/deb/bin/datashare b/datashare-dist/src/main/deb/bin/datashare
--- a/datashare-dist/src/main/deb/bin/datashare
+++ b/datashare-dist/src/main/deb/bin/datashare
@@ -6,6 +6,17 @@ mkdir -p "${DATASHARE_HOME}"/dist "${DATASHARE_HOME}"/index "${DATASHARE_HOME}"/
 DATASHARE_JAR=/usr/share/java/datashare.jar
 JAVA=${JAVA_HOME:-/usr}/bin/java
 
+if [ ! -f "$DATASHARE_JAR" ]; then
+  echo "$DATASHARE_JAR: not found, trying in this directory"
+  JAR_PATTERN="datashare-dist-*-all.jar"
+  JARS=( $JAR_PATTERN )
+  DATASHARE_JAR="$PWD/${JARS[0]}"
+  if [ ! -f "$DATASHARE_JAR" ]; then
+    echo "$DATASHARE_JAR: not found"
+    exit 2
+  fi
+fi
+
 cd "${DATASHARE_HOME}" || exit
 
 ${JAVA} -DPROD_MODE=true -Dfile.encoding=UTF-8 -Djava.system.class.loader=org.icij.datashare.DynamicClassLoader -cp ./dist:"${DATASHARE_JAR}" org.icij.datashare.Main \
